name: CommandSign
main: net.avatar.realms.spigot.commandsign.CommandSign
version: 0.0.1
commands:
    commandsign:
        description: Command Signs commands.
        aliases: [arcs, cmdsign]
        usage: |
             /<command> create
             /<command> edit
             /<command> delete
