name: CommandSign
main: net.avatar.realms.spigot.commandsign.CommandSign
author: Nokorbis
version: 1.2.7
website: https://www.spigotmc.org/resources/command-signs.10512/
softdepend: [Multiverse-Core, Vault]
commands:
    commandsign:
        description: Command Signs commands.
        aliases: [arcs, cmdsign]
        usage: |
             /<command> info
             /<command> create
             /<command> copy
             /<command> edit
             /<command> delete
