name: CommandSign
main: net.avatar.realms.spigot.commandsign.CommandSign
version: 1.2.7
softdepend: [Multiverse-Core, Vault]
commands:
    commandsign:
        description: Command Signs commands.
        aliases: [arcs, cmdsign]
        usage: |
             /<command> info
             /<command> create
             /<command> copy
             /<command> edit
             /<command> delete
